title: Fantasy Football Tiers
description: Weekly fantasy football tier rankings
baseurl: "/fantasy-football-tiers"
url: "https://mglusker.github.io"

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
